### ISSUE TITLE
routes pour les différentes requetes sur la BDD

### ISSUE THREAD

**Issue by charlineBx** [Medic-Assist/project#3]

**Comment by charlineBx** [comment]
voir branch : 
3-routes-pour-les-différentes-requetes-sur-la-bdd

**Comment by Dinholu** [comment]
Done 
Rdv par patient
CRUD RDV
adresse tempo

**Comment by Dinholu** [comment]
Ajouter 
- StatusTrajet lié au RDV

EstParti bool
PartiA DateTime Quand il a notifié qu'il est parti 
RetardPössible / bool 
Raison 
EstimationRetard 
Annulation rdv??

**Comment by charlineBx** [comment]
(ajouter un table Type_RDV / Presta_CentreMed:
idCentreMed
idTypeRDV
intitule
)
